name: Final VAPT Scan
on:
  push:
    branches: [main]
  workflow_dispatch: {}
jobs:
  blackducksca:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5
      - name: extra
        run: echo ${{ github.run_id }}
        uses: blackduck-inc/black-duck-security-scan@v2
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}

